# Generated by Django 3.2.9 on 2022-07-26 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220716_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='screenshots_taken',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
