# Generated by Django 3.2.9 on 2022-07-27 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_screenshots_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='screenshots_taken',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Screenshots Taken'),
        ),
    ]
