# Generated by Django 3.2.9 on 2022-09-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_coursesgroup'),
        ('users', '0005_auto_20220909_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='courses_groups',
            field=models.ManyToManyField(to='courses.CoursesGroup'),
        ),
    ]
