# Generated by Django 3.2.9 on 2022-09-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_coursesgroup'),
        ('users', '0006_auto_20220924_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses_groups',
            field=models.ManyToManyField(blank=True, null=True, to='courses.CoursesGroup'),
        ),
    ]
