# Generated by Django 3.2.9 on 2022-08-08 21:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='extra_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
