# Generated by Django 3.2.9 on 2022-09-09 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20220909_1809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_banks', '0003_alter_question_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionResult',
            new_name='QuestionAnswer',
        ),
    ]
