# Generated by Django 3.2.9 on 2022-09-21 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20220915_0122'),
        ('question_banks', '0004_rename_questionresult_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='courses.quiz'),
        ),
    ]
