# Generated by Django 3.2.9 on 2022-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_banks', '0005_alter_questionanswer_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
