# Generated by Django 3.2.9 on 2022-09-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_banks', '0006_question_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='image',
            new_name='explanation_image',
        ),
    ]
