# Generated by Django 3.2.9 on 2022-07-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20220730_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollment',
            old_name='is_enrolled_for_life_long',
            new_name='lifetime_enrollment',
        ),
    ]
