# Generated by Django 3.2.9 on 2022-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_is_enrolled_for_life_long_courseenrollment_lifetime_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='force_expiry',
            field=models.BooleanField(default=False, help_text='<strong class="text-warning">\n            &#x26A0; When checked, \n            This enrollment will be expired before its expiry date even if it is lifetime enrollment.\n            </strong>'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='<strong class="text-warning">&#x26A0; When not ckecked, this enrollment will be deactivated.</strong>'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='enrollment_duration_type',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=10, null=True),
        ),
    ]
