# Generated by Django 3.2.9 on 2022-08-15 21:18

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_auto_20220815_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_courseenrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
