# Generated by Django 3.2.9 on 2022-07-29 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='lecture',
            new_name='lectures',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user', 'name')},
        ),
    ]
