# Generated by Django 3.2.9 on 2022-07-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20220729_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='lecture',
            new_name='lectures',
        ),
    ]
