# Generated by Django 3.2.9 on 2022-07-28 23:12

import alteby.utils.version_format_validator
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('screenshots_limit', models.IntegerField(blank=True, null=True, verbose_name='Screenshots Limit')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_online', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('downtime_till', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'App Status',
                'verbose_name_plural': 'App Status',
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version_name', models.CharField(error_messages={'unique': 'This app version name is already exists'}, help_text='App Version Format', max_length=100, unique=True, validators=[alteby.utils.version_format_validator.VersionFormatValidator()], verbose_name='Version Name')),
                ('version_code', models.IntegerField(blank=True, db_index=True, unique=True, verbose_name='Version Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_minimum_version', models.BooleanField(default=False, verbose_name='Is Minimum Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
            },
        ),
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
