# Generated by Django 3.2.9 on 2022-07-25 22:01

import alteby.utils.version_format_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_name', models.CharField(error_messages={'unique': 'This app version name is already exists'}, help_text='App Version Format', max_length=100, unique=True, validators=[alteby.utils.version_format_validator.VersionFormatValidator()], verbose_name='Version Name')),
                ('version_code', models.IntegerField(blank=True, db_index=True, unique=True, verbose_name='Version Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_minimum_version', models.BooleanField(default=False, verbose_name='Is Minimum Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
            },
        ),
    ]
