# Generated by Django 3.2.9 on 2022-07-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_online', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('downtime_till', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'App Status',
                'verbose_name_plural': 'App Status',
            },
        ),
        migrations.AlterField(
            model_name='appversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
