# Generated by Django 3.2.9 on 2022-09-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220728_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='is_under_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
