# Generated by Django 3.2.9 on 2022-07-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220725_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='downtime_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
