# Generated by Django 3.2.9 on 2022-07-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220728_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100),
        ),
    ]
