# Generated by Django 3.2.9 on 2022-07-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_discussion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='attachements_available_for_enrolled_users_only',
            field=models.BooleanField(default=True, verbose_name='Attachements Available for Enrolled Users Only'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='downloadable_for_enrolled_users_only',
            field=models.BooleanField(default=True, verbose_name='Downloadable for Enrolled Users Only'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='is_attachements_available',
            field=models.BooleanField(default=True, verbose_name='Is Attachemets Available'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='is_downloadable',
            field=models.BooleanField(default=True, verbose_name='Is Downloadable'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='is_quiz_available',
            field=models.BooleanField(default=True, verbose_name='Is Quiz Available'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='quiz_available_for_enrolled_users_only',
            field=models.BooleanField(default=True, verbose_name='Quiz Available for Enrolled Users Only'),
        ),
    ]
