# Generated by Django 3.2.9 on 2022-07-24 01:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220724_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
