# Generated by Django 3.2.9 on 2022-07-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lecture_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='courses.lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
