# Generated by Django 3.2.9 on 2022-07-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220729_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy',
            name='period_type',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('weak', 'Weak'), ('month', 'Month'), ('year', 'Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='option',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared'), ('limited_period', 'Limited Period')], default='private', max_length=15),
        ),
    ]
