# Generated by Django 3.2.9 on 2022-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220729_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacy',
            name='attachements_available_for_enrolled_users_only',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='downloadable_for_enrolled_users_only',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='quiz_available_for_enrolled_users_only',
        ),
        migrations.AddField(
            model_name='privacy',
            name='enrollment_period',
            field=models.IntegerField(blank=True, help_text='The period that the course will be availabe for the user form the date of the enrollment when the course was free.', null=True, verbose_name='When avilable for free, users can enroll it for'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='enrollment_period_type',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('weak', 'Weak'), ('month', 'Month'), ('year', 'Year')], max_length=10),
        ),
        migrations.AddField(
            model_name='privacy',
            name='is_attachements_available_for_enrolled_users_only',
            field=models.BooleanField(default=True, verbose_name='Is Attachements Available for Enrolled Users Only'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='is_downloadable_for_enrolled_users_only',
            field=models.BooleanField(default=True, verbose_name='Is Downloadable for Enrolled Users Only'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='is_quiz_available_for_enrolled_users_only',
            field=models.BooleanField(default=True, verbose_name='Is Quiz Available for Enrolled Users Only'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='option',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared'), ('limited_period', 'Public (for Limited Period)')], default='private', max_length=15),
        ),
    ]
