# Generated by Django 3.2.9 on 2022-07-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lectureexternallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureexternallink',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
