# Generated by Django 3.2.9 on 2022-07-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20220729_1822'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discussion',
            name='courses_dis_object__9c3fe4_idx',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='object_type',
        ),
        migrations.AddField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='courses.lecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='courses.topic'),
            preserve_default=False,
        ),
    ]
