# Generated by Django 3.2.9 on 2022-07-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220724_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('arabic', 'Arabic'), ('english', 'English'), ('mixed', 'Mixed')], default='arabic', max_length=20),
        ),
    ]
