# Generated by Django 3.2.9 on 2022-07-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220729_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePrivacy',
        ),
        migrations.DeleteModel(
            name='LecturePrivacy',
        ),
    ]
