# Generated by Django 3.2.9 on 2022-07-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220730_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Privacy',
        ),
    ]
