# Generated by Django 3.2.9 on 2022-07-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_courseprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseprice',
            unique_together={('course', 'currency')},
        ),
    ]
