# Generated by Django 3.2.9 on 2022-07-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_courseprice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureexternallink',
            name='site_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
