# Generated by Django 3.2.9 on 2022-07-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20220730_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachement',
        ),
    ]
