# Generated by Django 3.2.9 on 2022-07-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='body',
        ),
    ]
