# Generated by Django 3.2.9 on 2022-07-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_courseattachement_lectureattachement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
