# Generated by Django 3.2.9 on 2022-07-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_rename_comment_body_comment_body'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['object_type', 'object_id'], name='courses_com_object__87a34f_idx'),
        ),
    ]
