# Generated by Django 3.2.9 on 2022-08-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_auto_20220807_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lecture'),
        ),
    ]
