# Generated by Django 3.2.9 on 2022-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20220808_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprivacy',
            name='enrollment_period',
        ),
        migrations.RemoveField(
            model_name='courseprivacy',
            name='enrollment_period_type',
        ),
        migrations.RemoveField(
            model_name='courseprivacy',
            name='period',
        ),
        migrations.RemoveField(
            model_name='courseprivacy',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='enrollment_period',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='enrollment_period_type',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='period',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='period_type',
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Must be set when choosing public (for a limited duration) option.', null=True),
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Must be set when choosing public (for a limited duration) option.', max_length=10),
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='enrollment_duration',
            field=models.IntegerField(blank=True, help_text='\n    The duration that the course will be availabe for the user form the date of the enrollment when the course was free.\n    Must be set when choosing public (for limited duration) option.\n    ', null=True, verbose_name='When avilable for free, users can enroll it for'),
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='enrollment_duration_type',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Must be set when choosing public (for a limited duration) option.', max_length=10),
        ),
        migrations.AddField(
            model_name='lectureprivacy',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Must be set when choosing public (for a limited duration) option.', null=True),
        ),
        migrations.AddField(
            model_name='lectureprivacy',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Must be set when choosing public (for a limited duration) option.', max_length=10),
        ),
        migrations.AddField(
            model_name='lectureprivacy',
            name='enrollment_duration',
            field=models.IntegerField(blank=True, help_text='\n    The duration that the course will be availabe for the user form the date of the enrollment when the course was free.\n    Must be set when choosing public (for limited duration) option.\n    ', null=True, verbose_name='When avilable for free, users can enroll it for'),
        ),
        migrations.AddField(
            model_name='lectureprivacy',
            name='enrollment_duration_type',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Must be set when choosing public (for a limited duration) option.', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseprivacy',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Must be set when choosing public (for a limited duration) option.', null=True),
        ),
        migrations.AlterField(
            model_name='courseprivacy',
            name='option',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared'), ('limited_duration', 'Public (for a Limited duration)')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='lectureprivacy',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Must be set when choosing public (for a limited duration) option.', null=True),
        ),
        migrations.AlterField(
            model_name='lectureprivacy',
            name='option',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared'), ('limited_duration', 'Public (for a Limited duration)')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='courseactivity',
            index=models.Index(fields=['user', 'course'], name='courses_cou_user_id_d3c415_idx'),
        ),
        migrations.AddIndex(
            model_name='courseactivity',
            index=models.Index(fields=['user'], name='courses_cou_user_id_a2c1af_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['topic'], name='courses_lec_topic_i_4528eb_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['duration'], name='courses_lec_duratio_2973ed_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['unit'], name='courses_top_unit_id_d5de3d_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['course'], name='courses_uni_course__baa35a_idx'),
        ),
    ]
