# Generated by Django 3.2.9 on 2022-09-09 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0025_auto_20220815_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureOverlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='courseactivity',
            name='courses_cou_user_id_d3c415_idx',
        ),
        migrations.RemoveField(
            model_name='courseactivity',
            name='course',
        ),
        migrations.AddField(
            model_name='lectureoverlap',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lectureoverlaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectureoverlap',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_topics', to='courses.lecture'),
        ),
        migrations.AddField(
            model_name='lectureoverlap',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lectures', to='courses.topic'),
        ),
        migrations.AddField(
            model_name='lectureoverlap',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_lectureoverlaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lectureoverlap',
            index=models.Index(fields=['topic'], name='courses_lec_topic_i_afa3de_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureoverlap',
            index=models.Index(fields=['lecture'], name='courses_lec_lecture_9dfe2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lectureoverlap',
            unique_together={('topic', 'lecture')},
        ),
    ]
