# Generated by Django 3.2.9 on 2022-09-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_banks', '0004_rename_questionresult_questionanswer'),
        ('courses', '0027_auto_20220910_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='question_banks.Question'),
        ),
    ]
