# Generated by Django 3.2.9 on 2022-09-23 16:11

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20220915_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprivacy',
            name='is_downloadable',
        ),
        migrations.RemoveField(
            model_name='courseprivacy',
            name='is_downloadable_for_enrolled_users_only',
        ),
        migrations.RemoveField(
            model_name='courseprivacy',
            name='is_quiz_available',
        ),
        migrations.RemoveField(
            model_name='courseprivacy',
            name='is_quiz_available_for_enrolled_users_only',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='enrollment_duration',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='enrollment_duration_type',
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='\n        Is used when using (for a limited duration) option.\n        Numbers in %\n        ', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Is used when using (for a limited duration) option.'),
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='show_contact_admin_on_free_enrollment',
            field=models.BooleanField(default=True, help_text='On uncheck this option, the user can enroll the course automatically when it is free.', verbose_name='Show Contact Admin Button on Free Enrollment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseprivacy',
            name='enrollment_duration',
            field=models.IntegerField(blank=True, help_text='\n            The duration that the course will be availabe for the user form the date of the enrollment when the course was free.\n            Must be set when choosing public (for limited duration) option.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
