# Generated by Django 3.2.9 on 2022-09-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20220923_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
