# Generated by Django 3.2.9 on 2022-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_lecturequality_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprivacy',
            name='is_attachements_available',
        ),
        migrations.RemoveField(
            model_name='courseprivacy',
            name='is_attachements_available_for_enrolled_users_only',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='is_attachements_available',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='is_attachements_available_for_enrolled_users_only',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='is_downloadable',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='is_downloadable_for_enrolled_users_only',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='is_quiz_available',
        ),
        migrations.RemoveField(
            model_name='lectureprivacy',
            name='is_quiz_available_for_enrolled_users_only',
        ),
        migrations.AddField(
            model_name='courseprivacy',
            name='attachments_status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Available for all users'), (2, 'Available ONLY for Enrolled Users')], default=2),
        ),
        migrations.AddField(
            model_name='lectureprivacy',
            name='attachments_status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Available for all users'), (2, 'Available ONLY for Enrolled Users')], default=2),
        ),
        migrations.AddField(
            model_name='lectureprivacy',
            name='download_status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Available for all users'), (2, 'Available ONLY for Enrolled Users')], default=2),
        ),
        migrations.AddField(
            model_name='lectureprivacy',
            name='quiz_status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Available for all users'), (2, 'Available ONLY for Enrolled Users')], default=2),
        ),
    ]
